#pragma once
#define _CRT_SECURE_NO_WARNINGS
#include "stdlib.h"
#include "stdio.h"
#include "conio.h"
#include "math.h"
#include "locale.h"
#include <string>
#include <iostream>
#include <iostream>
#include "windows.h"
#include "locale.h"